### ISSUE TITLE
1.19 Chest won't open 

### ISSUE THREAD

**Issue by SenorCyB** [GizmoTheMoonPig/luggage#5]
I would like to start by saying I am using the mod in a mod pack I created which might be messing with the luggage. The main problem I'm facing is that whenever I open the chest it instantaneously closes, not even a second to look at the inventory.  Are there any mods it's incompatible with? Is this a bug with 1.19?

**Comment by GizmoTheMoonPig** [comment]
I don't know of any incompatibilities. Can you let me know what modpack it is so I can check it out? I've never heard of an issue like this before

**Comment by BrainSlugs83** [comment]
Sometimes this happens to me too -- the chest just refuses to open... or sometimes the whistle won't summon it...

But I usually just forget about it for awhile and go somewhere else... and it eventually shows up and you can open it / whistle works again... (to be clear: whistle always makes the sound... just sometimes, the luggage won't come.)

**Comment by BrainSlugs83** [comment]
I tested this just now in 1.4.3 (Fabric) -- it seems to happen if I have anything equipped in my off hand... it might also happen other times, I'll need to play some more tonight and see.

**Comment by GizmoTheMoonPig** [comment]
oh, I know exactly why this is then. For some reason I was checking that both hands were empty before trying to open luggage. I don't know why the hell I did this, but I fixed it on forge about a week ago. I'll push for a fabric update as soon as I finish working on some more AI stuff and the wait key. Do let me know if it happens under any other circumstances as well and I'll look into them.

**Comment by BrainSlugs83** [comment]
Hmmm... yeah it still happens sometimes where it just won't open or respond to whistles... one time it turned black? -- I just went to sleep (in game), woke up and wandered off far enough away, and then it responded to whistles and would let me open it again...
![image](https://user-images.githubusercontent.com/5217366/186546023-32808049-8845-45d7-b6ae-24e22e44b0f6.png)

**Comment by GizmoTheMoonPig** [comment]
This has been fixed on both versions now that Fabric got a new build, just forgot to close this. Thanks for reporting!
